env: "prod" # local, dev, prod
# storage_path: "../../storage/storage.db"
storage_path: "./storage/storage.db"
http_server: 
  address: "0.0.0.0:8093"
  timeout: 4s
  idle_timeout: 30s
  user: "Shabby8574" 